language: go
go:
  - 1.9
install:
  - docker-compose up -d
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - ./enable-etcd-auth.sh
  - go test . ./vulcand/ ./vulcand/middleware
  - docker-compose down
sudo: required
services:
  - docker
notifications:
  email: false
