# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.8"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/mailgun/iptools"

[[constraint]]
  branch = "master"
  name = "github.com/mailgun/log"

[[constraint]]
  branch = "master"
  name = "github.com/mailgun/metrics"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  version = "v1.7.7"
  name = "github.com/mailgun/holster"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/Shopify/toxiproxy"
  version = "2.1.3"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"
